AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket with Site Hosting'

Parameters: #allows user to pass values into the template at the time of stack creation or update
  BucketName:
    Type: String
    Description: 'Please provide the bucket name'

Resources: #defines which resources will be created 
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration: #allows versioning to be configured 
        Status: Enabled
      WebsiteConfiguration: #specifies the index document for the static website
        IndexDocument: index.html
      PublicAccessBlockConfiguration: #configures public access settings for the bucket
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket #references the value of the bucket resource defined
      PolicyDocument:
        Id: Mypolicy
        Version: '2012-10-17'
        Statement: #The policy allows public read access to objects in the bucket
          - Sid: PublicReadGetObject
            Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
